BOT_TOKEN = ""

BOT_NAME = "flibusta_bot"

DB_NAME = BOT_NAME
DB_USER = BOT_NAME
DB_PASSWORD = ""
DB_HOST = ""
DB_PORT = ""

FLIBUSTA_SERVER = ""

WEBHOOK_PORT = 443
WEBHOOK_HOST = f"https://site.ru:{WEBHOOK_PORT}/{BOT_NAME}"
WEBHOOK_LISTEN = "0.0.0.0"

SERVER_HOST = "0.0.0.0"
SERVER_PORT = 7770

CHATBASE_API_KEY = ""
